a = '''Waste generation is practically inevitable in this growing world. Nearly 150,000 tonnes per day of solid waste is being generated in India alone. With this much amount of waste it is now more than important to develop our waste management techniques and implement them on large scales.
Moreover, waste could be a great source for resources as well. So, our aim should be to extract maximum out of it and generate minimum end product. We should try to follow 3 R’s (Reduce, Reuse, Recycle) before waste disposal. Only then we should move forward for material recovery and waste to energy.
Organic waste is approx. 60% of total solid waste generated in India. So proper disposal of organic waste is one of our biggest concern. Biogas production is one of the best method for organic waste disposal because at the end we are left with usable energy and organic fertilizers. Both of which are extremely important for us. But there are numerous challenges which need to be addressed before it could be viable.
CHALLENGES:
•	Ignorance:
One of the major challenges faced in biogas production is ignorance of this technology as viable option. People who could benefit most (e.g., rural areas) are either not aware of it or they just choose to ignore it. Since energy is available at relatively affordable prices nobody is willing to take an extra step for production of energy from biogas.
We need to make them aware of other benefits of biogas production apart from energy. Also, we should try to locate those remote areas where energy availability is still an issue. We can establish small scale digesters that are easy to use and maintain. 
•	Scalability:
Another important challenge that needs to be addressed is scalability of this technology. Most of the solid waste that is being generated are from urban areas. There is high population density so more waste is being generated but we can’t implement small scale digesters is cities, it is not a viable option. For that we need commercial bio-digesters which would cast a lot of initial cost and maintenance cost.
To improve scalability, we could establish multiple easy to use small biodigesters in nearest rural areas and drive all the collected organic waste from cities to those areas. Those biodigesters could be owned by farmers and they could have another source of income as well. Moreover, we could ask government to collaborate with farmers and provide them necessary resources.
'''
print(len(a.split()))